---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kafka-service.yaml
- kafka-headless.yaml
- kafka-config.yaml
- kafka-statefulset.yaml
- schema-registry.yaml
- schema-registry-service.yaml
- kafka-ui.yaml
- kafka-ui-service.yaml
- topic-job.yaml
