---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-variant
  namespace: default
data:
  CLUSTER_ID: xkaJModWQwCZYgqPx0gtow
  BROKER_COUNT: '3'
  TOPIC_REPLICATION_FACTOR: '3'
  KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-0.kafka-headless:9093,2@kafka-1.kafka-headless:9093,3@kafka-2.kafka-headless:9093
  KAFKA_DEFAULT_REPLICATION_FACTOR: '3'
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '3'
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '3'
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '2'
  KAFKA_MIN_INSYNC_REPLICAS: '2'
