---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-variant
  namespace: default
data:
  CLUSTER_ID: wJR2f7VATIuvdnLoUcuDXQ
  BROKER_COUNT: '1'
  TOPIC_REPLICATION_FACTOR: '1'
  KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-0.kafka-headless:9093
  KAFKA_DEFAULT_REPLICATION_FACTOR: '1'
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
  KAFKA_MIN_INSYNC_REPLICAS: '1'
