apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi # Redis snapshot storage is minimal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate # Ensures clean persistent volume unmounting/remounting
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:8.0-alpine # Tiny, secure, and blazing fast locally
          command: ["redis-server", "--appendonly", "yes"] # Enables AOF for better data persistence
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-local-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: LoadBalancer # Change from ClusterIP if you want to connect via localhost:6379 on your laptop
  ports:
    - name: redis-service-port
      port: 6379
      targetPort: 6379
  selector:
    app: redis
